### ISSUE TITLE
Batch export

### ISSUE THREAD

**Issue by briancantwe** [david-rhodes/GSOPs#1]
Hello!   Absolutely loving this toolset, it's just what I needed!  Really nice work.

At this point, I'm getting a bit complex.  I'm trying to export an animation back out to gaussian splats, but the export seems to only work on a per-frame basis.  Is there a way (or could a way be added) to export the entire frame range?

Thanks so much!

**Comment by david-rhodes** [comment]
Assuming you don't need more than 9999 frames, this should work: https://github.com/david-rhodes/GSOPs/commit/dd602979c4622725ffd788b1b0dd797199b998f6.

**Comment by briancantwe** [comment]
Excellent!  No, nothing that long, lol.  Thank you, I'll give it a whirl as soon as possible.

**Comment by briancantwe** [comment]
Ok!  Tested it out.  UI is crystal clear.  I think I might have hit a bug though.  It seems to want to export the current frame over and over again rather than the sequence.  I verified that my frame ranges and paths are correct and rebuilt the nodes from scratch a couple of times to sanity check.

**Comment by briancantwe** [comment]
Works perfectly!  Thanks so much for the insanely fast turnaround!

**Comment by david-rhodes** [comment]
You bet. Thanks for helping improve GSOPs!

**Comment by briancantwe** [comment]
Hello again!  Took me a bit to get back to it, vbut when I checked the exported splat ply's, it turned out they were all identical. Looks like it's exporting the current frame over and over again.  Ideas?  Thanks again!

**Comment by david-rhodes** [comment]
Hmm, interesting. Can you please try exporting from the `splat_relight` example scene and report if you see the same behavior?

I'm also curious what data you're changing per frame, and how it's computed. Is it all upstream from the export node? 

In the export code, I iterate through the frame range, set the current frame, then cook internal `EXPORT` node. I wonder if there's some dependency which isn't updating when setting the frame with `hou.setFrame()`?

**Comment by briancantwe** [comment]
Ah!  I discovered the problem was in my setup.  So sorry for the hassle.
Everything is working well now!  Case closed (again).

**Comment by david-rhodes** [comment]
No problem--thank you for following up!
