### ISSUE TITLE
Error when trying to view the splat with the GSplat Source SOP

### ISSUE THREAD

**Issue by oliverban** [david-rhodes/GSOPs#12]
I get this

GSplat Plugin [WARNING] [000000246CE6CF00] Spherical harmonics attributes 'sh1, sh2, ..., sh15' not found. Trying fallback f_rest_X attributes...
GSplat Plugin [INFO] [000000246CE6CF00] Spherical harmonics fallback 'f_rest_X' found.

I am using Postshot to get my splats. It works great, but the only way to export cameras is with ABC (Alembics) and not JSONs - I wonder if the error above comes from me not having the cameras!

**Comment by oliverban** [comment]
UPDATE: It works when I open your HIP and then replace the Koala with my own splat (and delete the camera node and wrangle). I've looked at both of them and they are now identical but somehow doesn't work when I build the network from scratch!

**Comment by david-rhodes** [comment]
No need to worry, @oliverban--this warning is just a reminder for Ruben and me to consistently name the spherical harmonics attributes. 

It may be that you need to disable lighting in your scene viewport. 
![image](https://github.com/user-attachments/assets/c38762a4-3d67-41e9-b44a-b7be1d01c050)

**Comment by oliverban** [comment]
> No need to worry, @oliverban--this warning is just a reminder for Ruben and me to consistently name the spherical harmonics attributes.
> 
> It may be that you need to disable lighting in your scene viewport. ![image](https://private-user-images.githubusercontent.com/23202691/391755588-c38762a4-3d67-41e9-b44a-b7be1d01c050.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxODUxODEsIm5iZiI6MTczMzE4NDg4MSwicGF0aCI6Ii8yMzIwMjY5MS8zOTE3NTU1ODgtYzM4NzYyYTQtM2Q2Ny00MWU5LWI0NGEtYjdiZTFkMDFjMDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDAwMTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1Mzg3YTU1NmYyMjMzOGY4ZWRmMzk2NWM2N2VmOGE5YmIyNDFjNjFiNzA5Y2JhZGU5YzFlNTkwODRjNDU4MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rccCK3gIFLY6lSB9J6w4ARJNnfeL68pG14QxW4R9a4I)

Welp! That was actually it! Great! It's working very nicely! I just saw Kiri Engine meshing 2.0, looks amazing! Any plans to have meshing as well? I guess some kind of VDB from Particles works for now, just was wondering! Thanks for this awesome pack btw, greatly appreciated!

**Comment by david-rhodes** [comment]
@oliverban glad to hear it's working now! Yeah, I've been working on coarse meshing utilities, which you can find a preview of in https://github.com/david-rhodes/GSOPs/tree/coarse-mesh-prep. There's a new example scene and several digital assets. Please give a test and report your findings. These are undocumented for now.

**Comment by TonyDua** [comment]
I apologize for replying to this closed issue again. I would like to know if this warning still exists in the latest version 2.0. Could you explain the current support for spherical harmonics in GSOP? I look forward to your reply @david-rhodes.

**Comment by david-rhodes** [comment]
> I apologize for replying to this closed issue again. I would like to know if this warning still exists in the latest version 2.0. Could you explain the current support for spherical harmonics in GSOP? I look forward to your reply @david-rhodes.

No worries. I replied to your question in Discord, but I'll also reply here for posterity: 

GSOPs currently supports 3rd order SH (45 f_rest_* attributes). If the ply file lacks these attributes, we simply use the f_dc_* attributes for the color, and the results become view independent. I was previously asked about support for 1st and 2nd order SH data in GSOPs (⁠general⁠), which are not explicitly supported throughout GSOPs, but it should be possible to add support (namely on import/export). However, for us to support such data, we require example scenes to work with (e.g., trained with --sh_degree 1 and --sh_degree 2).

GSOPs is 100% compatible with the (most common) 3DGS frameworks that you list. 

Finally, while we support SH, rotating the splat model in any way will currently "break" the view dependent colors.* Ruben and I are working on a solution to this problem, and we hope it will be included in the next release of GSOPs.

For simple rotation of a single 3DGS model, it's possible to offset the SH lookup direction vector to compensate, but we are referring to the "baking" of updated f_rest_* attributes. Postshot and Supersplat currently support this feature.

https://discord.com/channels/1278421597639671888/1324318647711305738
