### ISSUE TITLE
question of gaussian splats align by points node

### ISSUE THREAD

**Issue by macross27** [david-rhodes/GSOPs#3]
Hi! First of all, thank you for sharing your wonderful tools!
According to your documentation, "Rotating a splat model will not update spherical harmonics data accordingly. As a result, view-dependent lighting effects will not behave correctly in exported models.", is this mean using "gaussian splats align by points" node will break the spherical harmonics data? Thank you for your help!

**Comment by david-rhodes** [comment]
Hi @macross27,

You're welcome--thank you for your feedback!

Yes, rotating the model will break spherical harmonics data in the sense that the relationship between the camera and individual splats will now be different. I believe that Aras has solved this issue for the Unity Playground Project: https://github.com/aras-p/UnityGaussianSplatting. I would need to take a closer look to see how involved or complex his solution is, but I can offer workarounds in the meantime. Please tell me what your goal/use-case is, and I can offer appropriate suggestions. 

Thank you!

**Comment by macross27** [comment]
I was trying to clean the floating splats, correct the orientation of the gs, then upload to https://www.gracia.ai/ to see it in vr. Thanks!

**Comment by david-rhodes** [comment]
I see. So, my recommendation is to orient your model for cleanup, and then restore the original rotation before exporting. You can easily do this using the `xform` detail attribute which the `align_by_points` node creates. 

![gsops_issue](https://github.com/david-rhodes/GSOPs/assets/23202691/991050f1-1463-44f3-bc9f-e2fccc8e1b3d)

Hopefully you can reorient your model in Gracia's viewer/editor? If not, I believe the Unity project updates SH data when rotating the model, and it also has export support.

**Comment by david-rhodes** [comment]
@macross27 Hi again. Do you need any further assistance?

**Comment by macross27** [comment]
Unfortunately, Gracias's viewer doesn't have reorient functionality. So I am currently running some scripts during
"colmap" align process to output the correct orientation. Thank you for your support!

**Comment by david-rhodes** [comment]
Happy to help. Bummer that Gracia doesn't support rotation either...
