### ISSUE TITLE
GSOPs and Houdini Core

### ISSUE THREAD

**Issue by briancantwe** [david-rhodes/GSOPs#6]
Hello!   I've been using GSOPs for a while now and love it.  :-)   Up until now though I've been using Apprentice, but I now have access to a Core license.  It seems Houdini wants to drop into Apprentice mode as soon as I drop an GSOP import node.  Is there a way to get it working with Houdini Core?

Thanks!

**Comment by david-rhodes** [comment]
Thank you! 

Unfortunately, I would need to acquire a Core license myself to upgrade the otl licenses for use in this way. However, SideFX was kind enough to convert my H20 Tech Art Submission, which you can [download here](https://media.sidefx.com/uploads/contests/H20_techart_challenge/assets/utility_03_gsops.zip). Please note: this package is missing some of the updates that I committed to this repository after January 15th, 2024. 

Keep an eye on this repo or follow me on [LinkedIn ](https://www.linkedin.com/in/davidarhodes/)for potential news related to this . . .

**Comment by briancantwe** [comment]
Oh nice!  Looks like directly importing the hda files from that link
works!

**Comment by oliverban** [comment]
I also was wondering this, there's been so many updates since then and I would love to use it with Indie!

**Comment by david-rhodes** [comment]
Stay tuned for an upcoming announcement regarding this.

**Comment by david-rhodes** [comment]
We are thrilled to announce that GSOPs 2.0 is now available under the Houdini Commercial license! 

We're wishing you all a Merry Christmas and happy holidays!

**Comment by oliverban** [comment]
> We are thrilled to announce that GSOPs 2.0 is now available under the Houdini Commercial license!
> 
> We're wishing you all a Merry Christmas and happy holidays!

Amazing! Thanks so much! :D
